[DOC] documentation for contains, suffix and wildcard new features.
RediSearch/RediSearch pull request #2936
Opened 2022-07-26 07:14 UTC by ashtul

Including the new `WITHSUFFIXTRIE` keyword.

Related to #2774 #2886 #2932

@rrelledge

2022-07-26 15:26 UTC, rrelledge requested changes
Looks good to me. I left some suggestions for a couple of typo fixes and possible wording changes.

2022-07-26 15:26 UTC, rrelledge commented on docs/docs/reference/Query_Syntax.md
> +On suffix queries, the list of terms from the suffix term node will be use to create a union. On infix queries, the suffix terms is use as prefix on the trie, and all terms, from all matching nodes a
```suggestion
Suffix queries create a union of the list of terms from the suffix term node. Infix queries use the suffix terms as prefixes to the trie and create a union of all terms from all matching nodes.
```

2022-07-26 15:26 UTC, rrelledge commented on docs/docs/reference/Query_Syntax.md
> +Since version v2.6.0, the dictionary can be used for infix (contains) or suffix queries by appending `*` to the token. For example:
```suggestion
Since version v2.6.0, you can append `*` to the token to use the dictionary for infix (contains) or suffix queries. For example:
```

2022-07-26 15:26 UTC, rrelledge commented on docs/docs/reference/Query_Syntax.md
> +### Using a Suffix Trie
```suggestion
### Using a suffix trie
```

2022-07-26 15:26 UTC, rrelledge commented on docs/docs/reference/Query_Syntax.md
> +With suffix trie, the wildcard pattern is broken into tokens at every `*` character. A heuristic is used to choose the token with the least terms and each terms is matched with the wildcard pattern.
```suggestion
With a suffix trie, the wildcard pattern is broken into tokens at every `*` character. A heuristic is used to choose the token with the least terms, and each term is matched with the wildcard pattern.
```

2022-07-26 15:26 UTC, rrelledge commented on docs/docs/reference/Query_Syntax.md
> +These queries are CPU intensive as they require iteration over the the whole dictionary.
```suggestion
These queries are CPU intensive because they require iteration over the whole dictionary.
```

2022-07-26 15:26 UTC, rrelledge commented on docs/docs/reference/Query_Syntax.md
> +Note: all notes about prefix searches apply to infix/suffix queries.
```suggestion
Note: all notes about prefix searches also apply to infix/suffix queries.
```

2022-07-26 15:26 UTC, rrelledge commented on docs/docs/reference/Query_Syntax.md
> +An example for the syntax is `w'foo*bar?'`.
```suggestion
An example of the syntax is `w'foo*bar?'`.
```

2022-08-09 05:49 UTC, rafie approved these changes

2022-08-09 06:23 UTC, merged