Fix grammar and typos vectors.md
RediSearch/RediSearch pull request #3924
Opened 2023-10-06 16:32 UTC by adrianoamaral

adjusting grammar and typos on the changes for pre-filter query

**Describe the changes in the pull request**

A clear and concise description of what the PR is solving, including:
1. The current state briefly
2. What is the change
3. Adding the outcome (changed state)

**Which issues this PR fixes**
1. #...
2. MOD...

**Main objects this PR modified**
1. ...
2. ...

**Mark if applicable**

- [ ] This PR introduces API changes
- [ ] This PR introduces serialization changes

2023-10-11 21:16 UTC, dwdougherty commented on docs/docs/advanced-concepts/vectors.md
> +The definition of hybrid query combines different conditions and predicates with scoring methods from multiple fields in a compound score. These queries are executed against an index that encompasses
```suggestion
Hybrid queries combine different conditions and predicates with scoring methods from multiple fields in a compound score. These queries are executed against an index that encompasses both searchable field content and generated embeddings. With a single query, you can employ document selection and diverse scoring choices, consolidating the resulting scores using a chosen function to influence the relevance and importance of the results for a given use case.
```

2023-10-11 21:18 UTC, dwdougherty commented on docs/docs/advanced-concepts/vectors.md
> +Currently, Redis doesn't support Hybrid Queries with multiple scoring options. Redis approach combines pre-filtering documents against an index containing searchable fields (`TEXT`, `TAG`, `NUMERIC`,
```suggestion
Currently, Redis doesn't support hybrid queries with multiple scoring options. Redis's approach combines pre-filtering documents against an index containing searchable fields (`TEXT`, `TAG`, `NUMERIC`, `GEO`, `GEOSHAPE`, `VECTOR`) and generated embeddings, finding similarity between them according to the chosen algorithm (for example, KNN).
```

2023-10-11 21:20 UTC, dwdougherty commented on docs/docs/advanced-concepts/vectors.md
> +Pre-filter with a Vector Similarity KNN query syntax has a form of  `<primary_filter_query>=>[<vector_similarity_query>]`. The first part defines the document selection and filtering, and the second
```suggestion
Pre-filter with a vector similarity KNN query has the form `<primary_filter_query>=>[<vector_similarity_query>]`. The first part defines document selection and filtering, and the second part is represented by query modifier Attributes that define how similarity should be applied, in this case, KNN. Redis Stack has an internal mechanism for optimizing the computation of such queries. Two modes in which pre-filter queries are executed are:
```

2023-10-11 21:20 UTC, dwdougherty requested changes
Just a few changes.

2023-10-12 15:11 UTC, dwdougherty commented on docs/docs/advanced-concepts/vectors.md
> +Pre-filter with a vector similarity KNN query has the form `<primary_filter_query>=>[<vector_similarity_query>]`. The first part defines document selection and filtering, and the second part is repre
```suggestion
Pre-filter with a vector similarity KNN query has the form `<primary_filter_query>=>[<vector_similarity_query>]`. The first part defines document selection and filtering, and the second part is represented by query modifier attributes that define how similarity should be applied, in this case, KNN. Redis Stack has an internal mechanism for optimizing the computation of such queries. Two modes in which pre-filter queries are executed are:
```

2023-10-12 15:11 UTC, dwdougherty requested changes
Sorry... one more change

2023-10-12 15:27 UTC, adrianoamaral commented
Fixed, tsk

2023-10-12 15:27 UTC, dwdougherty approved these changes

2024-05-28 16:09 UTC, dwdougherty commented
The content in this PR will be merged to the new docs site.

2025-02-28 14:39 UTC, closed without merging