MOD-8391: Report active threads-indexes upon crash
RediSearch/RediSearch pull request #5403
Opened 2024-12-24 11:39 UTC by raz-mon

## Describe the changes in the pull request

This PR adds a global container holding a mapping between the active queries and the indexes they are working on, such that we can later add information to the logs in case of a crash (more use-cases may follow).

We add the thread to the global container for the following flows:
1. BG thread processing an `FT.SEARCH/AGGREGATE` command.
2. BG thread processing an `FT.CURSOR READ` command.
3. GC operation.
4. Index creation thread (indexer).
5. Main thread, when operating on an index (mainly in the shard, see comment below).

Notice:
1. We add the active thread to the global container only when it holds a StrongRef to it, since we will need to access Index data upon crashing, thus we must ensure that it exists (can't promote a WeakRef in the signal handler that is invoked after a crash).
2. Our main coverage is for the shard commands, as the coordinator commands are mostly stateless w.r.t the index on which they operate.
3. In the coordinator, we do not add the thread to the active-threads container in places that are not aware of the index the query is working on, such as the reducers of the `FT.INFO`, `FT.SEARCH` commands. The thread running the `FT.CURSOR` command is registered only for the `FT.CURSOR READ` subcommand.

#### Mark if applicable

- [ ] This PR introduces API changes
- [ ] This PR introduces serialization changes

2025-01-01 13:00 UTC, kei-nan requested changes

2025-01-01 13:00 UTC, kei-nan commented on src/spec.c
> +void IndexSpec_RemoveFromGlobals(StrongRef spec_ref, bool removeActive) {
not sure about tying thread stuff with index object.
Feels like we shouldn't tie them together

2025-01-02 07:04 UTC, raz-mon commented on src/activeThreads.c
> +ActiveThreads *activeThreads = NULL;
I prefer not having this kind of naming. Today it is easy to see that this variable is in global scope, so I prefer not overloading its name. Furthermore, if we add indicators for every variable characteristic they will become unreadable.

2025-01-02 07:06 UTC, raz-mon commented on src/activeThreads.c
> +  pthread_key_create(&_activeThreadKey, NULL);
Can you elaborate?
I want the scope of the link to be the same as the scope of the use of the StrongRef of the index by the thread.

2025-01-02 07:23 UTC, raz-mon commented on src/spec.c
> +void IndexSpec_RemoveFromGlobals(StrongRef spec_ref, bool removeActive) {
We release the strong ref here, which is also the latest time I want to be in the active-threads container.
If we don't do this, we miss some important coverage.

2025-01-02 13:20 UTC, kei-nan commented on src/activeThreads.c
I believe I commented on the variable names, here we are talking about file name.
I don't think we have such files in our repo, even if we did the overwhelming majority is using underscore opposed to camelCase.

2025-01-02 13:27 UTC, kei-nan commented on src/spec.c
> +void IndexSpec_RemoveFromGlobals(StrongRef spec_ref, bool removeActive) {
Remove from globals also gets called when the ref count reaches 0.
So it is possible that the same thread will call activeThreads_RemoveCurrentThread twice.

I think being strict here and knowing when we release will benefit us in the long run.

2025-01-02 13:33 UTC, kei-nan commented on src/info/info_redis.c
> +      RedisModule_InfoAddFieldULongLong(ctx, (const char *)spec->name, (unsigned long long)at->Ltid);
Consider outputting it in the same format redis outputs the thread ids in the crash log, would make our lives a bit easier.
e.g if they output it as hex then maybe output the id as a hex string.

2025-01-05 12:38 UTC, raz-mon commented on src/activeThreads.c
> +  pthread_key_create(&_activeThreadKey, NULL);
Notice the need for the StrongRef to be valid, which may not be the case after it is released in the thread.
I will add the assertion, seems the safest and most reasonable option.

2025-01-05 12:50 UTC, raz-mon commented on src/spec.c
> +void IndexSpec_RemoveFromGlobals(StrongRef spec_ref, bool removeActive) {
The trade-off of adding the argument for more coverage seems good to me, since in the release process many things can go wrong.
It's not that an argument is such a hustle or logic changer.
Don't you think the trade-off is worth it?

2025-01-05 19:36 UTC, raz-mon commented on src/info/info_redis.c
> +      RedisModule_InfoAddFieldULongLong(ctx, (const char *)spec->name, (unsigned long long)at->Ltid);
Yep, exactly why I added the linux `pid_t` thread-id in the Linux case (and printed in the same format).

2025-01-14 12:02 UTC, raz-mon commented on src/active_threads.c
> +  pthread_key_create(&_activeThreadKey, NULL);
Will think about it, I'm not sure it will have added value.

2025-01-14 12:05 UTC, raz-mon commented on src/spec.c
> +void IndexSpec_RemoveFromGlobals(StrongRef spec_ref, bool removeActive) {
I think this argument makes sense, as we are looking at the releasing flow of an index.
The alternative yields uncovered flows, which is not a good tradeoff IMO.
How would you do this otherwise, without loosing this coverage?

2025-03-11 13:16 UTC, raz-mon commented on src/active_queries/thread_info.c
> +    return;
Not sure we need this

2025-03-11 13:20 UTC, raz-mon commented on src/active_queries/thread_info.c
> +  assert(specRef.rm != NULL);
`assert` --> `RS_ASSERT`

2025-03-11 13:21 UTC, raz-mon commented on src/active_queries/thread_info.c
> +SpecInfo *CurrentThread_GetSpecInfo() {
Kind of a weird function.. Consider modifying it to only "get"

2025-03-11 13:24 UTC, raz-mon commented on src/active_queries/thread_info.c
> +void CurrentThread_SetIndexSpec(StrongRef specRef) {
Worth to mention that we require a StrongRef since we need to access the name of the index (currently that's the minimal information we need)

2025-03-11 13:24 UTC, raz-mon commented on src/active_queries/thread_info.h
> +#endif
Newline !!!!

2025-03-11 13:30 UTC, raz-mon commented on src/info/info_redis.c
> +  RedisModule_InfoAddSection(ctx, "active_queries");
I think we should have the same structure always, and have empty sections in case there is nothing to print for that section, such that we will have a consistent format.

2025-03-11 13:32 UTC, raz-mon commented on src/module.c
> +  // Prepare thread local storage for future threads
```suggestion
  // Prepare thread local storage for storing active queries/cursors
```

2025-03-11 16:46 UTC, kei-nan commented on src/active_queries/active_queries.c
> + * @brief Frees the active threads data structure.
Will keep the header comments, maintaining both is too error prone.

2025-03-11 17:06 UTC, kei-nan commented on src/active_queries/thread_info.c
> +void CurrentThread_SetIndexSpec(StrongRef specRef) {
Added a comment in the header file.

2025-03-11 17:10 UTC, kei-nan commented on src/active_queries/block_client.c
> +  RedisModule_BlockedClientMeasureTimeStart(blockedClient);
no changed needed in caller

2025-03-11 17:15 UTC, kei-nan commented on src/active_queries/active_queries.c
> +ActiveQueryNode* ActiveQueries_AddQuery(ActiveQueries* activeQueries, StrongRef spec, QueryAST* ast) {
I don't think we are running our tests with threads enabled.

2025-03-12 08:15 UTC, kei-nan commented on src/active_queries/active_queries.c
> +  dllist_init(&activeQueries->cursors);
I think the separation could be a good thing, we can bring it up for a team discussion.

2025-03-12 09:26 UTC, raz-mon commented on src/active_queries/active_queries.h
> +  QueryAST *ast;      // The query AST
Let's remove this, since it is unused.
We can add it when we'll need it.

2025-03-16 14:59 UTC, kei-nan commented on src/active_queries/thread_info.c
> +int ThreadLocalStorage_Init() {
renamed the function

2025-03-16 15:42 UTC, raz-mon commented on src/info/info_redis/info_redis.c
> +    RedisModule_InfoAddFieldCString(ctx, "index", spec ? spec->name : "n/a");
Will need to be obfuscated when the obfuscation pr is merged

2025-03-16 15:44 UTC, raz-mon commented on src/info/info_redis/info_redis.c
> +      RedisModule_InfoAddFieldCString(ctx, "index", specInfo->specName ? specInfo->specName : "n/a");
Will need to be obfuscated soon (just to note)

2025-03-16 15:46 UTC, raz-mon commented on src/info/info_redis/info_redis.c
> +    if (!spec) {
Would be nice to have some more documentation, for instance, when can this happen (`spec == NULL`)?

2025-03-17 07:48 UTC, kei-nan commented on src/info/info_redis/info_redis.c
> +      RedisModule_InfoAddFieldCString(ctx, "index", specInfo->specName ? specInfo->specName : "n/a");
yep, but as discussed this is out of scope for this PR.

2025-03-17 07:51 UTC, kei-nan commented on src/info/info_redis/info_redis.c
> +void AddToInfo_CurrentThread(RedisModuleInfoCtx *ctx) {
I think this information we are already getting from redis.
We know the thread that called this function is the one that crashed.
So if redis already marks the thread for us it seems pointless to print its thread id.

Anyhow this type of change is out of scope of this PR, IMHO.

2025-03-17 07:52 UTC, kei-nan commented on src/info/info_redis/info_redis.c
> +    RedisModule_InfoBeginDictField(ctx, buffer);
I don't think so, an index name is a constant thing which doesn't change from the creation point of the index.
If there are no data races on the specific variable then I think we don't need to lock at this present time.

2025-03-17 12:43 UTC, kei-nan commented on src/active_queries/active_queries.c
> +  dllist_init(&activeQueries->cursors);
for example you could have coordinator cursors.
The spec ref behaviour is a bit dfferent and the meaning of not having a spec ref means different things for cursors and queries.
That is just one difference, In general I think separating the stuff we need to analyse will provide more order in our analysis.

2025-03-17 16:03 UTC, raz-mon commented on src/info/info_redis/info_redis.c
> +void AddToInfo_CurrentThread(RedisModuleInfoCtx *ctx) {
We have them printed only for Linux platforms.
I think it's nice data to have in case it's not printed, but can drop it for now if you don't want to overload the PR.

2025-03-23 10:02 UTC, kei-nan commented on src/aggregate/aggregate_exec.c
> +    CurrentThread_ClearIndexSpec();
in this specific case by the caller, either due to a failure in building the request or when completing the request.

2025-03-23 14:10 UTC, oshadmi commented on src/aggregate/aggregate_plan.h
> +// TODO: The above works by accident.
Please replace comment with a ticket

2025-03-25 15:52 UTC, nafraf submitted a review, later dismissed

2025-03-26 14:58 UTC, nafraf submitted a review, later dismissed

2025-03-26 16:01 UTC, raz-mon commented on src/spec.c
> +StrongRef IndexSpecRef_Promote(WeakRef ref) {
Let's add some good documentation here - not a trivial function to call

2025-03-26 16:08 UTC, kei-nan commented on src/spec.c
> +StrongRef IndexSpecRef_Promote(WeakRef ref) {
added comments in the header file.

2025-03-30 12:25 UTC, kei-nan approved these changes
Roles got switched during development.
Approving on behalf of Raz.

2025-03-30 14:35 UTC, merged